# ---------------------------------------------
# site settings
# ---------------------------------------------

theme: jekyll-theme-minimal
title: Amber Jaura / Homepage
description: Bookmark the site for my project shares and updates

# ---------------------------------------------
# repo color themes off atm 
# ---------------------------------------------

# repo color theme
# repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
# repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
# repo_trophies:
#  enabled: true
#  theme_light: flat # https://github.com/ryo-ma/github-profile-trophy
#  theme_dark: gitdimmed # https://github.com/ryo-ma/github-profile-trophy

# ---------------------------------------------
# RSS feed
# ---------------------------------------------
# will use title and url fields
# https://github.com/jekyll/jekyll-feed re : customization


# ---------------------------------------------
# layout
# ---------------------------------------------


# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------


# sample_github_username : # _____
# linkedin_username: # ______
# x_username : # handle
# youtube_id : # yt channel id (youtube.com/@<youtubeid>)

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
keep_files:
  - CNAME
  - .nojekyll

# Plug-ins
plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ["robots.txt", "assets/js/search/*.js"]
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  enabled: [year, tags, categories] # enables year, tag and category archives (remove if you need to disable one of them).
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: "/blog/:year/"
    tag: "/blog/tag/:name/"
    category: "/blog/category/:name/"

display_tags: ["formatting", "images", "links", "math", "code", "blockquotes"] # these tags will be displayed on the front page of your blog
display_categories: ["external-services"] # these categories will be displayed on the front page of your blog

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Einstein]
  first_name: [Albert, A.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

# Display different badges withs stats for your publications
# Customize badge behavior in _layouts/bib.liquid
enable_publication_badges:
  altmetric: true # Altmetric badge (Customization options: https://badge-docs.altmetric.com/index.html)
  dimensions: true # Dimensions badge (Customization options: https://badge.dimensions.ai/)
  google_scholar: true # Google Scholar badge (https://scholar.google.com/intl/en/scholar/citations.html)
  inspirehep: true # Inspire HEP badge (https://help.inspirehep.net/knowledge-base/citation-metrics/)

# Filter out certain bibtex entry keywords used internally from the bib output
filtered_bibtex_keywords:
  [
    abbr,
    abstract,
    additional_info,
    altmetric,
    annotation,
    arxiv,
    award,
    award_name,
    bibtex_show,
    blog,
    code,
    google_scholar_id,
    html,
    inspirehep_id,
    pdf,
    poster,
    preview,
    selected,
    slides,
    supp,
    video,
    website,
  ]

# Maximum number of authors to be shown for each publication (more authors are visible on click)
max_author_limit: 3 # leave blank to always show all authors
more_authors_animation_delay: 10 # more authors are revealed on click using animation; smaller delay means faster animation

# Enables publication thumbnails. If disabled, none of the publications will display thumbnails, even if specified in the bib entry.
enable_publication_thumbnails: true

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

# These are the defaults
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:
